version: '3'
services:
  server:
    image: norcore/fictional-employee-db-server:1.0
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/fictional-employee-db
volumes:
  mongo-data: