name: CI/CD Pipeline

on:
  push:
    branches:
      - aws-s3-static  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies and build frontend
        working-directory: client
        run: |
          npm install
          npm run build
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          REACT_APP_FRONTEND_URL: ${{ secrets.REACT_APP_FRONTEND_URL }}

      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}

      - name: Build Backend Docker Image
        working-directory: server
        run: |
          docker build -t norcore/fictional-employee-db-server:${GITHUB_RUN_NUMBER} .
          docker push norcore/fictional-employee-db-server:${GITHUB_RUN_NUMBER}

      - name: Build Frontend Docker Image
        working-directory: client
        run: |
          docker build -t norcore/fictional-employee-db-client:${GITHUB_RUN_NUMBER} .
          docker push norcore/fictional-employee-db-client:${GITHUB_RUN_NUMBER}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools
          python3 -m pip install --user awscli
        
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Copy Files to S3 Bucket
        run: |
          aws s3 cp client/build s3://my-s3-bucket-rnorbi --recursive

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{secrets.AWS_EC2_SG}} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Create SSH private key file
        run: |
          echo "${{secrets.SSH_KEY}}" > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: SSH into your EC2 and Configure Dependencies
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@${{secrets.REACT_APP_BACKEND_URL}} 'bash -s' < dependencies.sh

      - name: SSH into your EC2 and Deploy Backend
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          REACT_APP_FRONTEND_URL: ${{ secrets.REACT_APP_FRONTEND_URL }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GITHUB_RUN_NUM: ${{ github.run_number }}
        run: |
          ssh -v -o StrictHostKeyChecking=no -o SendEnv="GITHUB_RUN_NUM MONGO_URI REACT_APP_FRONTEND_URL REACT_APP_BACKEND_URL" -i ssh_key.pem ubuntu@${{ env.REACT_APP_BACKEND_URL }} 'bash -s' < deploy.sh

      - name: Revoke runner IP address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{secrets.AWS_EC2_SG}} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Cleanup SSH key file
        run: |
          rm ssh_key.pem
