name: CI/CD Pipeline

on:
  push:
    branches:
      - aws-serverless

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies and build frontend
        working-directory: client
        run: |
          npm install
          npm run build
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          REACT_APP_FRONTEND_URL: ${{ secrets.REACT_APP_FRONTEND_URL }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-setuptools
          python3 -m pip install --user awscli
        
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Copy Files to S3 Bucket
        run: |
          aws s3 cp client/build s3://my-s3-bucket-rnorbi --recursive